services:
  uvic-course-api:
    build: .
    env_file: 
      - .env
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7.2-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"